### ISSUE TITLE
Map dataview variables to files where they appear

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/Obsidian.jl#10]

**Comment by neelsmith** [comment]
Here's how to recognize them (from the `dataview`  docs):

Dataview generates data from your vault by pulling information from Markdown frontmatter and Inline fields.

Markdown frontmatter is arbitrary YAML enclosed by --- at the top of a markdown document which can store metadata about that document.
Inline fields are a Dataview feature which allow you to write metadata directly inline in your markdown document via Key:: Value syntax.

Examples of both are shown below:

```
---
alias: "document"
last-reviewed: 2021-08-17
thoughts:
  rating: 8
  reviewable: false
---
```

# Markdown Page
```
Basic Field:: Value
**Bold Field**:: Nice!
You can also write [field:: inline fields]; multiple [field2:: on the same line].
If you want to hide the (field3:: key), you can do that too.
```
